identifier: k2n5x28fsbbf3ek2
allowErrorCollect: false
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: blog-new
homeFolder: D:\blog-new
distFolder: dist/blog-new
outDir: D:\blog-new\dist\static
handle404: ''
